foxy/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from auth import views as auth_view
from social import views as social_view

urlpatterns = [
    path('admin/', admin.site.urls),



    #auth
    path("login/", auth_view.Login.as_view(), name = "login"),
    path("logout/", auth_view.Logout.as_view(), name = "logout"),
    path("signup/", auth_view.Signup.as_view(), name = "signup"),

    #social
    path("accounts/profile/", social_view.Wall.as_view(), name = "accounts_profile"),
    path("profile/", social_view.Profile.as_view(), name = "profile"),
    path("post/", social_view.Post.as_view()),
    path("", social_view.Wall.as_view(), name = "home"),
    #like
    path("post/<int:pk>/like", social_view.PostLike.as_view()),
    #comment
    path("post/<int:pk>/comment", social_view.PostComment.as_view()),
    #add-friends
    path("add-friends/", social_view.addFriends),
    path("add/<int:id>", social_view.add, name="add"),
    #chat
    path("start-chat/<str:username>", social_view.chatPage, name="chat"),
    path("chat/", social_view.index, name = "chat_home")
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chat/models.py
from django.db import models

# Create your models here.
class ChatModel(models.Model):
    sender = models.CharField(max_length=100, default=None)
    message = models.TextField(null=True, blank = True)
    thread_name = models.CharField(max_length=100, null=True, blank = True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.message)

social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now = True)
    content = models.TextField()
    image = models.ImageField(blank = True)

    def __str__(self):
        return str(self.content)

class Friends(models.Model):
    person1 = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "person1")
    person2 = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "person2")

    def __str__(self):
        return str("%s-%s" %(self.person1, self.person2))

class Like(models.Model):
    post = models.ForeignKey("Post", on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return str("%s likes %s" %(self.user, self.post.content))

class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.CharField(max_length = 200)
    def __str__(self):
        return str(self.content)

social/forms.py
from django import forms
from social import models

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ["content", "image"]

class PostComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ["content"]

chat/views.py
from django.shortcuts import render

# Create your views here.

social/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import SingleObjectMixin
from social import models,forms
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from chat.models import ChatModel


# Create your views here.


User = get_user_model()

class Wall(LoginRequiredMixin, ListView):
    #queryset = models.Post.objects.all()
    template_name = "social/wall.html"
    context_object_name = "posts"
    login_url = "login/"

    def get_queryset(self):
        #models.Friends.objects.create(person1= User.objects.get(id = 1), person2= self.request.user)
        friendIds = []
        for friend in models.Friends.objects.filter(person1 = self.request.user):
            friendIds.append(friend.person2.id)
        for friend in models.Friends.objects.filter(person2 = self.request.user):
            friendIds.append(friend.person1.id)

        #posts = models.Post.objects.filter(user = 2)
       
        #print(user__person1)
        
        return models.Post.objects.filter(user__in = friendIds).order_by("-created_at")

class Profile(LoginRequiredMixin, ListView):
    login_url = "login/"
    template_name = "social/profile.html"
    context_object_name = "posts"

    def get_queryset(self):
        return models.Post.objects.filter(user = self.request.user).order_by("-created_at")

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        data["post_form"] = forms.PostForm()
        return data

class Post(View):
    def post(self, request):
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit = False)
            post.user = request.user
            post.save()

        return redirect("/profile/")

class PostLike(View):
    model = models.Post
    def post(self, request, pk):
        models.Like.objects.create(post=self.model.objects.get(pk = pk), user=request.user)
        return HttpResponse(code = 204)

class PostComment(View):
    model = models.Post
    form = forms.PostComment
    def post(self, request, pk):
        post = self.model.objects.get(pk = pk)
        form = self.form(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.user = request.user
            comment.save()
            #return redirect('/')
            return HttpResponse(status = 204)
        print(form.errors)
        return HttpResponse(code = 400)


def addFriends(request):

    friendIds = []
    for friend in models.Friends.objects.filter(person1 = request.user):
        friendIds.append(friend.person2.id)
    for friend in models.Friends.objects.filter(person2 = request.user):
        friendIds.append(friend.person1.id)
    friendIds.append(request.user.id)

    persons = models.User.objects.exclude(id__in = friendIds)
    #persons = models.Post.objects.filter(user__in = friendIds).order_by("-created_at")
    
    context = {
        "persons": persons
    }
    return render(request, "social/add_friends.html", context)

def add(request, id):
    print(id)
    #models.Friends.objects.create(person1= User.objects.get(id = 1), person2= self.request.user)
    models.Friends.objects.create(person1=request.user, person2=User.objects.get(id = id))
    return redirect("/add-friends")



#for chats
def index(request):
    friendIds = []
    for friend in models.Friends.objects.filter(person1 = request.user):
        friendIds.append(friend.person2.id)
    for friend in models.Friends.objects.filter(person2 = request.user):
        friendIds.append(friend.person1.id)
    users = User.objects.filter(id__in = friendIds)
    #sending friend ids
    context = {"users": users,}
    return render(request, "chat/index_chat.html", context)


def chatPage(request, username):

    friendIds = []
    for friend in models.Friends.objects.filter(person1 = request.user):
        friendIds.append(friend.person2.id)
    for friend in models.Friends.objects.filter(person2 = request.user):
        friendIds.append(friend.person1.id)
    users = User.objects.filter(id__in = friendIds)
    user_obj = User.objects.get(username = username)
    
    if request.user.id > user_obj.id:
        thread_name = "chat_%s-%s" %(request.user.id, user_obj.id)
    else:
        thread_name = "chat_%s-%s" %(user_obj.id, request.user.id)
    

    message_obj = ChatModel.objects.filter(thread_name=thread_name)

    context = { "users": users, "user":user_obj, "messages":message_obj}
    return render(request, "chat/main_chat.html", context)


    

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CollegeBuddy</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">


    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
        integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
        crossorigin="anonymous" /> -->
    


    {% block css %} 
    {% endblock %}
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo">CollegeBuddy</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a href="/profile/">{{ request.user.username }}</a></li>
                <li><a href="/add-friends/">Add Friends</a></li>
                <li><a href="/chat/">Chat</a></li>
                <li><a href="/logout/">Logout</a></li>
                
                {% else %}
                <li><a href="/login/">Login</a></li>
                <li><a href="/signup/">SignUp</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>


    {% block content %}
    {% endblock %}


    {% block javascript %}
    {% endblock %}

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.modal');
            var instances = M.Modal.init(elems);
        });
    </script>
    <script src="/static/social/social.js"></script>
</body>

</html>

templates/chat/index_chat.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'chat/index.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top" style="background-color: tomato;"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'chat/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url "chat" user.username %}">{{user.username}}</a></td>
                            </tr>
                            {% endfor %}

                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

templates/chat/main_chat.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static 'chat/index.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="back-container">
    <div class="container-fluid front-container">
        <div class="back-top" style="background-color: orange;"></div>
        <div class="back-main"></div>
    </div>
    <div class="container front-container1">
        <div class="row chat-top" style="margin-bottom: 0px;">
            <div class="col-sm-4 border-right border-secondary">
                <img src="{% static 'chat/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{request.user.username}}</span>


            </div>
            <div class="col-sm-8">
                <img src="{% static 'chat/dp.png' %}" alt="" class="profile-image rounded-circle">
                <span class="ml-2">{{user.username}}</span>
                
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 contacts">
                <div class="contact-table-scroll">
                    <table class="table table-hover">
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><img src="{% static 'chat/dp.png' %}" alt="" class="profile-image rounded-circle">
                                </td>
                                <td><a href="{% url "chat" user.username %}">{{user.username}}</a></td>
                            </tr>
                            {% endfor %}

                            <!-- end -->
                        </tbody>
                    </table>
                </div>

            </div>
            <div class="col-sm-8 message-area">
                <div class="message-table-scroll">
                    <table class="table">
                        <tbody id='chat-body'>
                            {% for message in messages %}
                            {% if message.sender == request.user.username %}
                            <tr>
                                <td>
                                    <p class="bg-success p-2 mt-2 mr-5 shadow-sm text-white float-right rounded">
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>
                                    <p class="bg-primary p-2 mt-2 mr-5 shadow-sm text-white float-left rounded">
                                        {{message.message}}
                                    </p>
                                </td>
                                <td>
                                    <p><small class="p-1 shadow-sm">{{message.timestamp|time:'H:i'}}</small>
                                    </p>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="row message-box p-3">
                    
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="message_input" placeholder="Write message...">

                    </div>
                    <div class="col-sm-2 mt-1">
                        <div class="control">
                            <button class="btn btn-success" id="chat-message-submit">Send</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>
{{user.id|json_script:"json-username"}}
{{request.user.username|json_script:"json-message-username"}}
{% endblock %}

{% block javascript %}
<script src={% static 'chat/chat.js' %}></script>
{% endblock %}

templates/social/add_friends.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        {{user.username}}
        <ul class="collection with-header">
            <li class="collection-header"><h4>Add Friends...</h4></li>

            {% for person in persons %}
                <li class="collection-item">
                    <div class="row">
                        <div class="col s6">{{person.username}}</div>
                        
                        <div class="col s6" style="text-align: end;">
                            <a href="{% url "add" person.id %}">
                                <button type="submit" class="waves-effect waves-light btn">ADD</button>
                            </a>
                            
                        </div>
                        
                    </div>

                </li>
            {% endfor %}
        </ul>
    </div>
    
{% endblock %}

templates/social/components/post.html
<div class="container" style="margin-top: 1cm;">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-panel green accent-2">
                    <span class="card-title" style="font-weight:400;">{{post.user.username}}</span>
                    {% if post.image %}
                    <div class="card-image">
                        <img src="/media/{{ post.image }}" style="width: auto; margin-top: 10px;">

                    </div>
                    {% endif %}

                    <div class="card-content">
                        <p>{{post.content}}</p>
                        <p>{{post.created_at}}</p>
                    </div>
                    <div class="card-action">

                        <a href="#" onclick="likePost({{post.id}});"><strong style="color: crimson;">{{post.like_set.count}} LIKEs </strong>
                        </a>

                        <a class="modal-trigger" href="#postModal{{post.id}}"><strong style="color: crimson;">{{post.comment_set.count}} COMMENTS</strong></a>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div id="postModal{{post.id}}" class="modal">
    <div class="modal-content">
        <h4>Comments</h4>
        <ul>
            {% for comment in post.comment_set.all %}
                <li>
                    {{comment.user}} - {{comment.content}}
                    <hr>
                </li>
            {% endfor %}
        </ul>
        <form action="" method="post" onsubmit="commentPost({{post.id}}, document.getElementById('comment{{post.id}}').value)">
            {% csrf_token %}
            <class="input-field col s6">
                <input placeholder="Add Comment here..." id="comment{{post.id}}" type="text" class="validate">
                <!-- <label for="comment{{post.id}}">Comment</label> -->
                <button type="submit" >COMMENT!</button>
              </div>
        </form>
    </div>
</div>

templates/social/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h4 style="font-style: italic; font-family: cursive;">PROFILE</h4>
        <form action="/post/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ post_form }}
            <div class="row" style="text-align: end;">
                <button type="submit" class="btn waves-effect">POST</button>
            </div>
            
            
        </form>
    </div>



    {% for post in posts %}
        {% include "social/components/post.html" %}
    {% endfor %}


{% endblock %}

templates/social/wall.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h3 style="font-style: italic; font-family: cursive;" >wall</h3>
    </div>
    
    {% for post in posts %}
        {% include "social/components/post.html" %}
    {% endfor %}

{% endblock %}